import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
const summary=JSON.parse(await readFile(new URL('../public/spain-summary.json',import.meta.url),'utf8'));
test.use({serviceWorkers:'block'});
for(const locale of ['de','es','en-GB','en-US'])test(`CIS refreshed data, copy and layout agree in ${locale}`,async({page},testInfo)=>{
  if(locale === 'en-US') await page.emulateMedia({colorScheme: 'dark'});
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto(`/?country=es&view=spain-issues&lang=${locale}`);
  const root=page.locator('.spain-issues-page');await expect(root).toBeVisible();
  await expect(root.locator('.spain-concern-ranking').first().locator(':scope > div')).toHaveCount(8);
  await expect(root.locator('.spain-concern-ranking').nth(1).locator(':scope > div')).toHaveCount(8);
  const pct=value=>new Intl.NumberFormat(locale,{maximumFractionDigits:1}).format(value)+'%';
  const issue=summary.issues;
  await expect(root.locator('.spain-economy-summary')).toContainText(pct(issue.economy.personal.good+issue.economy.personal.veryGood));
  await expect(root.locator('.spain-economy-summary')).toContainText(pct(issue.economy.country.good+issue.economy.country.veryGood));
  await expect(root).not.toContainText(/3557|64[,.]7|April 2026|abril de 2026/);
  await root.locator('.economy-view-toggle button').nth(1).click();
  await expect(root.locator('.economic-perception-bar').first().locator('i')).toHaveCount(7);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
  await page.evaluate(()=>scrollTo(0,0));
  await page.screenshot({path:testInfo.outputPath(`cis-${locale}.png`),fullPage:true});
  const info=root.locator('#spain-national-concerns details').first();
  await info.locator('summary').click();
  const dialog=page.getByRole('dialog',{name:'Info',exact:true});
  await expect(dialog).toContainText(issue.study);
  await expect(dialog.locator(`a[href="${issue.technicalUrl}"]`)).toHaveCount(1);
  await expect(dialog).not.toContainText('3557');
  expect(errors).toEqual([]);
});
