import { test, expect } from '@playwright/test';
import { readFile } from 'node:fs/promises';
const source = await readFile(new URL('../src/main.jsx', import.meta.url), 'utf8');
const admin = source.match(/const BUG_REPORT_DASHBOARD_PATH = "([^"]+)"/)[1];
test.use({ serviceWorkers: 'block' });
test('Studio wins, feedback waits, notices do not repeat across reloads', async ({ page }, info) => {
  await page.clock.install();
  await page.goto('/?view=studio&lang=de');
  await expect(page.locator('.studio-search input')).toBeVisible();
  await page.clock.runFor(9000);
  const studio = page.locator('[data-notice="studio-guide-v1"]');
  await expect(studio).toBeVisible();
  await expect(page.locator('.studio-announcement')).toHaveCount(1);
  await studio.getByRole('button', { name: 'Einführung ausblenden' }).click();
  await page.clock.runFor(57000);
  await expect(page.locator('.studio-announcement')).toHaveCount(0);
  await page.clock.runFor(4000);
  const feedback = page.locator('[data-notice="feedback-v1"]');
  await expect(feedback).toBeVisible();
  await page.screenshot({ path: info.outputPath('feedback-notice.png') });
  await feedback.getByRole('button', { name: 'Feedback geben' }).click();
  await expect(page).toHaveURL(/page=bug-report/);
  await expect(page.locator('.studio-announcement')).toHaveCount(0);
  await page.goto('/?view=studio&lang=de');
  await page.clock.runFor(125000);
  await expect(page.locator('.studio-announcement')).toHaveCount(0);
});
test('feedback waits for a modal to close and fits the viewport', async ({ page }, info) => {
  await page.clock.install();
  await page.goto('/?lang=es');
  await expect(page.locator('.site-header')).toBeVisible();
  await page.evaluate(() => { const d=document.createElement('dialog'); d.id='notice-test-modal'; document.body.append(d); d.showModal(); });
  await page.clock.runFor(65000);
  await expect(page.locator('.studio-announcement')).toHaveCount(0);
  await page.evaluate(() => document.querySelector('#notice-test-modal').remove());
  await page.clock.runFor(1000);
  const notice = page.locator('[data-notice="feedback-v1"]');
  await expect(notice).toContainText('Enviar comentarios');
  const b=await notice.boundingBox(), size=page.viewportSize();
  expect(b.x).toBeGreaterThanOrEqual(0); expect(b.x+b.width).toBeLessThanOrEqual(size.width);
  await page.screenshot({path:info.outputPath('feedback-spanish.png')});
  await page.clock.runFor(17000);
  await expect(notice).toHaveCount(0);
});
for (const status of [401,403,429,503]) test(`admin diagnoses HTTP ${status} distinctly`, async ({page}) => {
  await page.route('**/api/bug-reports?*', route=>route.fulfill({status,json:{error:'test'}}));
  await page.goto(admin+'?lang=de');
  await page.getByLabel('Dashboard key').fill(' synthetic-test-key ');
  const request=page.waitForRequest('**/api/bug-reports?*');
  await page.getByRole('button',{name:'Open dashboard',exact:true}).click();
  expect((await request).headers()['x-pollframe-admin-key']).toBe('synthetic-test-key');
  await expect(page.getByRole('alert')).toContainText({401:'nicht gültig',403:'Sicherheitsdienst',429:'15 Minuten',503:'nicht verfügbar'}[status]);
});
test('dashboard separates notice rates and leaves zero denominators empty', async ({page}) => {
  const day=new Date().toISOString().slice(0,10);
  await page.route('**/api/bug-reports?*',route=>route.fulfill({json:{reports:[],stats:{total:0}}}));
  await page.route('**/api/analytics',route=>route.fulfill({json:{days:{[day]:{notice_studio_shown:10,notice_studio_dismissed:2,notice_studio_clicked:3}}}}));
  await page.goto(admin+'?lang=de');
  await page.getByLabel('Dashboard key').fill('test');
  await page.getByRole('button',{name:'Open dashboard',exact:true}).click();
  const stats=page.locator('.notice-stats');
  await expect(stats).toContainText('2 · 20 %'); await expect(stats).toContainText('3 · 30 %');
  await expect(stats.getByRole('row').filter({hasText:'Feedback'})).toContainText('—');
});
