import {test,expect} from '@playwright/test';
const url='/?view=studio&template=history-original&lang=de&editor=1&workspace=edit&range=five';
test('real catalogue: generate, pin, exclude, undo, reload and PNG retain the actual layout',async({page},info)=>{
  await page.goto(url);
  const svg=page.locator('.studio-current-preview-image > svg');
  await expect(svg).toHaveAttribute('data-direct-edit-ready','true');
  const labels=()=>svg.getAttribute('data-labelled-events');
  expect((await labels()).split(',').length).toBeGreaterThanOrEqual(4);
  expect(await labels()).toContain('ukraine');
  const tools=page.locator('.studio-inspector-panel');
  await tools.getByRole('button',{name:'Ereignisse',exact:true}).click();
  await expect(tools.getByRole('slider',{name:'Ereignis-Ebenen'})).toHaveCount(0);
  await tools.getByRole('button',{name:'3 Beschriftungsebenen',exact:true}).click();
  const before=await labels();
  await tools.getByRole('button',{name:'Anordnung erzeugen',exact:true}).click();
  await expect(page.locator('[data-assistant-state]')).toHaveAttribute('data-assistant-state',/"historyEventSeed":1/);
  const generated=await labels();
  await page.keyboard.press('Control+z');
  await expect(svg).toHaveAttribute('data-labelled-events',before);
  await page.keyboard.press('Control+Shift+z');
  await expect(svg).toHaveAttribute('data-labelled-events',generated);
  await tools.getByRole('button',{name:/Ereignisse auswählen/}).click();
  const cat=page.getByRole('dialog',{name:'Ereignisse auswählen'});
  await cat.getByRole('searchbox').fill('Ukraine');
  const row=cat.locator('[data-catalogue-event="ukraine"]');
  const reloads=[];
  page.on('request',r=>{if(r.url().includes('studioHistorySource'))reloads.push(r.url());});
  await row.getByRole('button',{name:'Ausschließen',exact:true}).click();
  await expect(svg).not.toHaveAttribute('data-labelled-events',/ukraine/);
  await row.getByRole('checkbox').check();
  await expect(cat).toBeVisible();
  await expect(page.locator('dialog[open]')).toHaveCount(1);
  expect(reloads).toEqual([]);
  const lane=row.getByRole('combobox',{name:/Ebene für/});
  await lane.click();await cat.getByRole('option',{name:'Ebene 3',exact:true}).click();
  await expect(svg.locator('[data-event-id=ukraine]')).toHaveAttribute('data-event-lane','2');
  await cat.getByRole('button',{name:'Fertig',exact:true}).click();
  await tools.getByRole('button',{name:'Anordnung erzeugen',exact:true}).click();
  await expect(svg.locator('[data-event-id=ukraine]')).toHaveAttribute('data-event-lane','2');
  const persistent=await labels();
  await page.reload();await expect(svg).toHaveAttribute('data-labelled-events',persistent);
  const overlaps=await svg.locator('.event-label-bg').evaluateAll(nodes=>nodes.flatMap((a,i)=>{const r=a.getBoundingClientRect();return nodes.slice(i+1).filter(b=>{const q=b.getBoundingClientRect();return Math.min(r.right,q.right)>Math.max(r.left,q.left)+1&&Math.min(r.bottom,q.bottom)>Math.max(r.top,q.top)+1;}).map(()=>true);}));
  expect(overlaps).toEqual([]);
  await page.getByRole('button',{name:'PNG herunterladen',exact:true}).click();
  const png=page.getByRole('dialog',{name:'PNG exportieren'});
  await expect(png.locator('svg[data-labelled-events]')).toHaveAttribute('data-labelled-events',persistent);
  await page.screenshot({path:info.outputPath('real-events-export.png')});
});

test('short date range explains missing data instead of pretending more layers create events',async({page})=>{
  await page.goto(url.replace('range=five','range=custom')+'&start=2024-01-01&end=2024-01-07');
  const svg=page.locator('.studio-current-preview-image > svg');await expect(svg).toBeVisible();
  const tools=page.locator('.studio-inspector-panel');await tools.getByRole('button',{name:'Ereignisse',exact:true}).click();
  await expect(tools).toContainText('Mehr Ebenen erzeugen keine zusätzlichen Daten');
  await tools.getByRole('button',{name:'Fünf Jahre ansehen',exact:true}).click();
  await expect.poll(async()=>((await svg.getAttribute('data-labelled-events'))||'').split(',').filter(Boolean).length).toBeGreaterThanOrEqual(4);
});
