import{test,expect}from'@playwright/test';
test.use({serviceWorkers:'block'});
test('preview groups tools before publishing, hides sign-in and theme; editor retains theme',async({page},info)=>{
  await page.addInitScript(()=>localStorage.setItem('pollframe-notice-dismissed:studio-guide-v1','yes'));
  await page.goto('/?view=studio&lang=en-GB&template=poll-classic&editor=1');
  await expect(page.locator('.studio-current-preview-image svg')).toBeVisible();
  await expect(page.locator('.account-entry')).toHaveCount(0);
  const header=page.locator('.studio-current-preview > header');
  expect(await header.getByRole('button').allTextContents()).toEqual(['Info','Edit','Download PNG','Embed']);
  await expect(header.getByRole('button',{name:/^(Dark|Light)$/})).toHaveCount(0);
  const png=await header.getByRole('button',{name:'Download PNG'}).boundingBox(),embed=await header.getByRole('button',{name:'Embed',exact:true}).boundingBox();
  expect(Math.abs(png.y-embed.y)).toBeLessThan(2);
  await page.screenshot({path:info.outputPath('design-preview-controls.png')});
  await header.getByRole('button',{name:'Download PNG'}).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await expect(page.getByRole('dialog').getByRole('radiogroup',{name:'Appearance'})).toHaveCount(0);
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await header.getByRole('button',{name:'Embed',exact:true}).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await expect(page.getByRole('dialog').getByRole('button',{name:/^(Dark|Light)$/})).toHaveCount(0);
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await header.getByRole('button',{name:'Edit',exact:true}).click();
  await page.getByRole('button',{name:'Colours & background',exact:true}).click();
  await expect(page.locator('.studio-tools').getByRole('button',{name:'Dark',exact:true})).toBeVisible();
});
test('local Ctrl+I replays the drop without resetting dismissal or hijacking typing',async({page},info)=>{
  await page.addInitScript(()=>localStorage.setItem('pollframe-notice-dismissed:studio-guide-v1','yes'));
  await page.goto('/?view=studio&lang=en-GB');
  await expect(page.getByRole('searchbox')).toBeVisible();
  await expect(page.locator('.studio-announcement')).toHaveCount(0);
  await page.keyboard.press('Control+i');
  await expect(page.locator('.studio-announcement')).toBeVisible();
  expect(await page.evaluate(()=>localStorage.getItem('pollframe-notice-dismissed:studio-guide-v1'))).toBe('yes');
  await page.getByRole('button',{name:'Dismiss introduction'}).click();
  await page.getByRole('searchbox').focus();await page.keyboard.press('Control+i');
  await expect(page.locator('.studio-announcement')).toHaveCount(0);
  await page.getByRole('searchbox').blur();await page.keyboard.press('Control+i');
  await expect(page.locator('.studio-announcement')).toBeVisible();
  await page.screenshot({path:info.outputPath('announcement-demo.png')});
});
test('phone preview has no sign-in or editor-only controls and publish buttons fit',async({page},info)=>{
  await page.setViewportSize({width:390,height:844});
  await page.addInitScript(()=>localStorage.setItem('pollframe-notice-dismissed:studio-guide-v1','yes'));
  await page.goto('/?view=studio&lang=de&template=poll-classic&editor=1');
  await expect(page.locator('.studio-current-preview-image svg')).toBeVisible();
  const header=page.locator('.studio-current-preview > header');
  await expect(header.getByRole('button',{name:'Bearbeiten',exact:true})).toHaveCount(0);
  await expect(page.locator('.account-entry')).toHaveCount(0);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
  await page.screenshot({path:info.outputPath('phone-preview-controls.png')});
});
