// Kept in the lazy account bundle, not the country-page startup bundle.
export const ACCOUNT_COPY = {
  "Kontozugang": ["Account access", "Acceso a la cuenta"],
  "Anmelden": ["Sign in", "Iniciar sesión"],
  "Registrieren": ["Register", "Registrarse"],
  "Passwort vergessen": ["Forgot password", "¿Has olvidado tu contraseña?"],
  "Anzeigename": ["Display name", "Nombre público"],
  "Test-E-Mail": ["Test email", "Correo de prueba"],
  "E-Mail": ["Email", "Correo electrónico"],
  "Neues Passwort": ["New password", "Nueva contraseña"],
  "Passwort": ["Password", "Contraseña"],
  "Passwort verbergen": ["Hide password", "Ocultar contraseña"],
  "Passwort anzeigen": ["Show password", "Mostrar contraseña"],
  "Verbergen": ["Hide", "Ocultar"],
  "Anzeigen": ["Show", "Mostrar"],
  "Bitte warten…": ["Please wait…", "Espera un momento…"],
  "Testkonto erstellen": ["Create test account", "Crear cuenta de prueba"],
  "Konto erstellen": ["Create account", "Crear cuenta"],
  "Link anfordern": ["Request link", "Solicitar enlace"],
  "Passwort ändern": ["Change password", "Cambiar contraseña"],
  "Lokalen Test-Postausgang öffnen": ["Open local test outbox", "Abrir la bandeja de salida de prueba local"],
  "Bestätigungslink erneut anfordern": ["Request another confirmation link", "Solicitar otro enlace de confirmación"],
  "Angemeldet als": ["Signed in as", "Sesión iniciada como"],
  "Lokale Designs und Stile im Konto sichern": ["Back up local designs and styles to your account", "Guardar los diseños y estilos locales en tu cuenta"],
  "Abmelden": ["Sign out", "Cerrar sesión"],
  "Stil": ["Style", "Estilo"],
  "Design": ["Design", "Diseño"],
  "Lokal übernehmen": ["Save a local copy", "Guardar una copia local"],
  "Öffnen": ["Open", "Abrir"],
  "Löschen": ["Delete", "Eliminar"],
  "Noch keine Dateien in diesem Konto.": ["No files in this account yet.", "Todavía no hay archivos en esta cuenta."],
  "Konto verwalten": ["Manage account", "Gestionar cuenta"],
  "Kontodaten herunterladen": ["Download account data", "Descargar los datos de la cuenta"],
  "Konto löschen…": ["Delete account…", "Eliminar cuenta…"],
  "Mit deinem Passwort bestätigen": ["Confirm with your password", "Confirma con tu contraseña"],
  "Konto endgültig löschen": ["Permanently delete account", "Eliminar la cuenta definitivamente"],
  "Bestätigung": ["Confirmation", "Confirmación"],
  "Passwort zurücksetzen": ["Reset password", "Restablecer contraseña"],
  "Link verwenden": ["Use link", "Usar enlace"],
  "Lokaler Test-Postausgang — keine echten E-Mails": ["Local test outbox — no real emails", "Bandeja de prueba local — no se envían correos reales"],
  "Im lokalen Test nur erfundene Adressen mit .test verwenden.": ["Use fictional .test addresses for local testing only.", "Para la prueba local, usa solo direcciones ficticias terminadas en .test."],
  "Passwortmanager und Einfügen sind möglich.": ["Password managers and pasting are supported.", "Puedes usar un gestor de contraseñas y pegar texto."],
  "Mindestens 15 Zeichen; Passwortmanager und Einfügen sind möglich.": ["At least 15 characters; password managers and pasting are supported.", "Al menos 15 caracteres; puedes usar un gestor de contraseñas y pegar texto."],
  "Öffentliche Konten sind noch nicht freigeschaltet. Deine Designs bleiben weiterhin lokal verfügbar.": ["Public accounts are not enabled yet. Your designs remain available locally.", "Las cuentas públicas aún no están habilitadas. Tus diseños siguen disponibles en este dispositivo."],
  "Der Kontodienst ist gerade nicht erreichbar. Bitte später erneut versuchen.": ["The account service is unavailable. Please try again later.", "El servicio de cuentas no está disponible. Inténtalo de nuevo más tarde."],
  "Zu viele Versuche. Bitte eine Minute warten.": ["Too many attempts. Please wait a minute.", "Demasiados intentos. Espera un minuto."],
  "Anfrage fehlgeschlagen.": ["Request failed.", "No se pudo completar la solicitud."],
  "Das hat nicht geklappt.": ["That did not work. Please try again.", "No se pudo completar la operación. Inténtalo de nuevo."],
  "Der Kontodienst antwortet nicht rechtzeitig. Bitte noch einmal versuchen.": ["The account service took too long to respond. Please try again.", "El servicio de cuentas ha tardado demasiado en responder. Inténtalo de nuevo."],
  "Bitte die Testadresse über den lokalen Postausgang bestätigen. Es wird keine echte E-Mail verschickt.": ["Confirm the test address through the local outbox. No real email is sent.", "Confirma la dirección de prueba en la bandeja local. No se envía ningún correo real."],
  "Bitte bestätige deine E-Mail-Adresse über den Link in deinem Posteingang, bevor du dich anmeldest.": ["Confirm your email using the link in your inbox before signing in.", "Antes de iniciar sesión, confirma tu correo mediante el enlace de tu bandeja de entrada."],
  "Wenn dieses Testkonto existiert, liegt ein Link im lokalen Postausgang.": ["If this test account exists, a link is in the local outbox.", "Si existe esta cuenta de prueba, encontrarás un enlace en la bandeja local."],
  "Wenn ein Konto zu dieser Adresse existiert, erhältst du einen Link zum Zurücksetzen. Prüfe auch deinen Spamordner.": ["If an account exists for this address, you will receive a reset link. Check your spam folder too.", "Si existe una cuenta con esta dirección, recibirás un enlace para restablecer la contraseña. Revisa también la carpeta de spam."],
  "Passwort geändert. Bestehende Sitzungen wurden widerrufen.": ["Password changed. Existing sessions have been revoked.", "Contraseña cambiada. Se han cerrado las sesiones existentes."],
  "Falls eine Bestätigung erforderlich ist, wurde ein neuer Link angefordert.": ["If confirmation is needed, a new link has been requested.", "Si es necesario confirmar la dirección, se ha solicitado un nuevo enlace."],
  "Stil als neue lokale Kopie gespeichert.": ["Style saved as a new local copy.", "Estilo guardado como una nueva copia local."],
  "Nur diese Datei aus dem Konto löschen? Lokale Kopien bleiben erhalten.": ["Delete only this file from the account? Local copies will remain.", "¿Eliminar solo este archivo de la cuenta? Se conservarán las copias locales."],
  "Konto und gespeicherte Dateien gelöscht. Lokale Kopien auf deinem Gerät bleiben erhalten.": ["Account and stored files deleted. Local copies on your device remain.", "Se han eliminado la cuenta y sus archivos guardados. Se conservan las copias locales de tu dispositivo."],
  "Dein Konto und seine gespeicherten Designs und Stile werden dauerhaft gelöscht. Dies lässt sich nicht rückgängig machen.": ["Your account and its saved designs and styles will be permanently deleted. This cannot be undone.", "Tu cuenta y sus diseños y estilos guardados se eliminarán definitivamente. Esta acción no se puede deshacer."],
  "Neues Testpasswort eingeben.": ["Enter a new test password.", "Introduce una nueva contraseña de prueba."],
  "Bestätigungslink ungültig oder abgelaufen.": ["Confirmation link is invalid or expired.", "El enlace de confirmación no es válido o ha caducado."],
  "Testadresse bestätigt. Du kannst dich anmelden.": ["Test address confirmed. You can sign in.", "Dirección de prueba confirmada. Ya puedes iniciar sesión."],
  "Invalid email or password": ["Invalid email or password", "Correo o contraseña incorrectos"],
  "Email not verified": ["Email not verified", "Correo sin verificar"],
  "Invalid token": ["Invalid or expired link", "Enlace no válido o caducado"],
};
export function accountText(l, text) {
  const translated = ACCOUNT_COPY[text];
  return translated ? l(text, ...translated) : text;
}
