import React from "react";

// Spanish version of the existing notice. Provider names, addresses, links,
// retention periods and legal references are preserved, not paraphrased away.
export default function SpanishPrivacyPage({email}) {
  return <main className="legal-page privacy-page" id="top">
    <a className="breadcrumb" href="/?lang=es">← Volver al resumen</a>
    <p className="section-label">Información legal</p>
    <h1>Política de privacidad</h1>
    <p>Puedes <a href="?page=datenschutz&lang=es&analytics=off">excluir este navegador de nuestras estadísticas de visitas</a> o <a href="?page=datenschutz&lang=es&analytics=on">volver a incluirlo</a>. Para ello, Pollframe guarda únicamente una preferencia de activación o desactivación en este dispositivo. No es un identificador y no se envía a nuestros contadores. Al borrar los datos del sitio se elimina la preferencia. Las estadísticas técnicas de solicitudes de Cloudflare no se ven afectadas.</p>
    <p className="privacy-updated">Actualización: 28 de septiembre de 2026</p>
    <section><h2>1. Responsable del tratamiento</h2>
      <address>Katharina O&apos;Connor<br/>Kaiserallee 2b<br/>23570 Lübeck<br/>Alemania</address>
      <p>Correo electrónico: <a href={`mailto:${email}`}>{email}</a></p>
    </section>
    <section><h2>2. Alojamiento y distribución</h2>
      <p>Pollframe se distribuye mediante Cloudflare Workers con Static Assets, un servicio de Cloudflare, Inc. Para ofrecer y proteger el sitio, Cloudflare trata datos técnicos de conexión. Entre ellos pueden figurar la dirección IP, la hora de acceso, el archivo solicitado, el estado HTTP, el volumen de datos transferidos, información sobre el navegador y el dispositivo y, si el navegador lo facilita, la página de procedencia.</p>
      <p>La base jurídica es el artículo 6, apartado 1, letra f, del RGPD. Nuestros intereses legítimos son ofrecer un servicio fiable, protegerlo frente a ataques y diagnosticar fallos técnicos. No mantenemos una base de datos propia de visitantes ni analizamos por nuestra cuenta registros de acceso sin agregar.</p>
      <p>Los límites de solicitudes utilizan valores hash de IP con un componente secreto, separados de la analítica: intervalos de 60 segundos en el perímetro y de 15 minutos para la administración. Los contadores caducados se eliminan.</p>
      <p>Cloudflare opera una red mundial, por lo que también puede haber tratamiento fuera del Espacio Económico Europeo. Describe las garantías para estas transferencias en su <a href="https://www.cloudflare.com/cloudflare-customer-dpa/" target="_blank" rel="noreferrer">acuerdo de tratamiento de datos</a> y su <a href="https://www.cloudflare.com/policies/privacy/" target="_blank" rel="noreferrer">política de privacidad</a>.</p>
    </section>
    <section><h2>3. Aplicación y datos guardados en tu dispositivo</h2>
      <p>Studio guarda en este dispositivo los diseños, estilos reutilizables, archivos importados y hasta 40 identificadores de plantillas abiertas recientemente. Esta lista permite ordenar por «Vistos recientemente» y no se envía a nuestra analítica. Los borradores locales no constituyen una copia de seguridad de una cuenta entre dispositivos.</p>
      <p>Pollframe guarda en el almacenamiento local del navegador los ajustes que eliges —idioma, apariencia y tamaño del texto— y la última instantánea de encuestas mostrada. La lista de seguimiento solo se ofrece al abrir Pollframe como aplicación instalada. Sus entradas contienen únicamente los parlamentos y partidos elegidos y los últimos valores de comparación; no se envían a Pollframe ni se sincronizan entre dispositivos. Una referencia limitada a la sesión mantiene estables los cambios mientras la aplicación sigue abierta y caduca al terminar esa sesión del navegador o tras 24 horas. Un trabajador de servicio y la caché del navegador conservan los archivos de la aplicación y los resúmenes básicos necesarios para funcionar sin conexión. La aplicación instalada también prepara para uso sin conexión los archivos de encuestas nacionales de Alemania, Reino Unido y España, las series de los estados alemanes, los datos regionales españoles, los resultados de circunscripciones británicas. En un navegador normal, los conjuntos detallados se guardan en caché solo después de usarlos.</p>
      <p>Si activas las alertas del dispositivo, el navegador solicita permiso para las notificaciones. Pollframe comprueba los cambios de la lista de seguimiento mientras la aplicación está abierta. Los cambios ya mostrados se marcan localmente como vistos y no generan una alerta posterior del sistema. Un registro local conservado durante un máximo de 14 días evita alertas duplicadas al reiniciar la aplicación. Actualmente no hay notificaciones push en segundo plano cuando la aplicación está cerrada. No se guarda ninguna suscripción push ni dirección de entrega de notificaciones en un servidor de Pollframe.</p>
      <p>Estos archivos permanecen en tu dispositivo hasta que se sustituyen automáticamente o eliminas la aplicación o los datos del sitio de Pollframe. La biblioteca guardada no se sube ni se utiliza para identificarte. Al abrir o compartir enlaces configurados de Studio, los ajustes y textos propios incluidos en la URL se transmiten a Pollframe y, al compartirlos, al destinatario. No incluyas información confidencial. Los archivos locales de imágenes y fuentes importados no se incluyen en esas URL.</p>
    </section>
    <section><h2>4. Cookies, medición de audiencia y publicidad</h2>
      <p>Para cada aviso informativo (introducción a Studio o invitación a enviar comentarios), contamos por separado las visualizaciones, los cierres explícitos y los clics en el enlace como totales diarios, sin vincularlos a una persona. Los indicadores locales y un límite de tiempo evitan avisos repetidos o simultáneos; estos valores funcionales nunca se envían a la analítica. La exclusión de analítica también se aplica a estos contadores.</p>
      <p>También contamos una sesión de lectura cualificada cuando una página permanece visible durante al menos 60 segundos y recibe una interacción indicada por el navegador. Solo se envía el contador; no se registran teclas, posiciones del puntero ni secuencias de acciones. Es un indicador de uso, no una prueba de que haya una persona ni una impresión publicitaria. Las solicitudes de analítica de automatizaciones conocidas y las direcciones IP internas configuradas expresamente se excluyen antes del almacenamiento. Las cabeceras de conexión se examinan de forma transitoria, sin incorporarlas al conjunto estadístico. Un navegador desconocido o una visita de una sola página no se considera automáticamente un bot.</p>
      <p>Pollframe utiliza Cloudflare Web Analytics, de Cloudflare, Inc., para medir visitas y páginas vistas de forma agregada y conocer los dominios de procedencia, países, categorías de dispositivos y navegadores, rendimiento de carga y Core Web Vitals. Usamos estas mediciones agregadas para mejorar el alcance, la facilidad de uso y el rendimiento técnico de Pollframe. El componente de medición se carga desde <code>static.cloudflareinsights.com</code> y envía mediciones a <code>cloudflareinsights.com</code>. No se carga en la inserción específica para periodistas.</p>
      <p>Cloudflare declara que Web Analytics no utiliza cookies ni almacenamiento local, no sigue a las personas entre sitios y no recoge ni utiliza datos personales de los visitantes. No se registran los parámetros de las URL. Pollframe no recibe direcciones IP ni identificadores que permitan reconocer a una persona. La base jurídica es el artículo 6, apartado 1, letra f, del RGPD; nuestros intereses legítimos son medir el alcance de forma agregada respetando la privacidad y mejorar el sitio.</p>
      <p>Cloudflare conserva los datos de medición sin muestrear durante siete días y posteriormente conserva datos agregados; los informes del panel están disponibles durante un máximo de seis meses. Consulta la <a href="https://developers.cloudflare.com/web-analytics/data-metrics/data-origin-and-collection/" target="_blank" rel="noreferrer">documentación de Web Analytics</a>. Pollframe no utiliza redes publicitarias, no vende datos personales ni toma decisiones automatizadas sobre sus visitantes.</p>
      <p>Pollframe también mantiene un contador propio deliberadamente limitado para mejorar el producto. Cuenta categorías generales de páginas —resúmenes de países, encuestas históricas, mapas, preocupaciones, valoración del Gobierno y lista de seguimiento—, instalaciones y aperturas de la aplicación instalada, páginas visibles durante 60 segundos y acciones expresas de publicación, como abrir los diálogos para compartir o exportar PNG, copiar enlaces, códigos de inserción o notas de fuentes e iniciar exportaciones PNG o CSV. Solo guarda la categoría predefinida, su total y el día del calendario UTC en un Cloudflare Durable Object restringido a la UE. No guarda direcciones IP, datos del navegador o dispositivo, direcciones de páginas, parámetros de URL, procedencias, cookies, valores del almacenamiento local ni otros identificadores. No crea perfiles ni reconoce visitantes que regresan. Las cifras cuentan acciones, no personas únicas; abrir la guía de instalación de iOS no cuenta como instalación. Los totales diarios se eliminan tras 400 días. La base jurídica es el artículo 6, apartado 1, letra f, del RGPD; nuestros intereses legítimos son conocer qué partes resultan útiles, comprobar las funciones de instalación y publicación y mejorar el servicio sin elaborar perfiles.</p>
    </section>
    <section><h2>5. Gráficos insertados y enlaces externos</h2>
      <p>La búsqueda de Studio es local. La clasificación «Populares» utiliza totales diarios de identificadores de plantillas públicas durante un máximo de 31 días naturales, sin búsquedas, contenido de diseños, direcciones IP ni identificadores de visitantes. Cuenta aperturas, no personas únicas. La exclusión de analítica también se aplica aquí. La base jurídica es el artículo 6, apartado 1, letra f, del RGPD para mejorar el servicio. Las fuentes de Studio se sirven desde Pollframe, no desde un proveedor externo.</p>
      <p>Las inserciones de Pollframe cargan gráficos y mapas directamente desde Pollframe a través de Cloudflare. No contienen publicidad ni seguimiento de terceros. Al seguir un enlace externo a una fuente o licencia, el proveedor de destino recibe los datos técnicos necesarios para cargar su sitio y los trata conforme a su propia política de privacidad.</p>
      <p>El buscador de circunscripciones británicas envía a Postcodes.io únicamente el código postal extraído de una dirección, su parte inicial o el término de lugar, después de pulsar «Buscar». Pollframe usa la respuesta para seleccionar la circunscripción y no conserva la búsqueda. Postcodes.io recibe los datos técnicos de conexión necesarios y los trata conforme a su propia <a href="https://postcodes.io/about" target="_blank" rel="noreferrer">información</a>. La búsqueda por nombre de circunscripción, incluida la tolerancia a errores ortográficos, se realiza localmente en tu navegador. No se ofrece búsqueda por código postal para Irlanda del Norte.</p>
    </section>
    <section><h2>6. Informes de problemas</h2>
      <p>El formulario separado de problemas envía a Pollframe el tipo seleccionado, la página afectada, el idioma, el tamaño de la ventana, la cadena de identificación del navegador y la nota opcional. No pide nombre ni correo. Cloudflare trata necesariamente los datos de conexión descritos en la sección 2. Pollframe transforma la IP en un valor irreversible con un componente secreto para limitar solicitudes, lo utiliza solo contra envíos automatizados repetidos y lo elimina al terminar el periodo de limitación de una hora.</p>
      <p>Los informes se guardan en un Cloudflare Durable Object privado y solo son visibles en el panel editorial protegido por contraseña. Los usamos para reproducir, priorizar y corregir problemas técnicos, visuales y de datos. La base jurídica es el artículo 6, apartado 1, letra f, del RGPD; nuestros intereses legítimos son garantizar la calidad y el funcionamiento seguro. Los informes se eliminan cuando dejan de ser necesarios y automáticamente en un plazo máximo de doce meses. No incluyas información personal ni sensible en la nota opcional.</p>
    </section>
    <section><h2>7. Contacto por correo electrónico</h2>
      <p>El asistente de contacto no transmite tus entradas a Pollframe ni a Cloudflare. Solo prepara un correo y solicita al navegador que abra tu aplicación de correo. Los datos se transmiten únicamente si envías el mensaje desde esa aplicación.</p>
      <p>Si nos contactas, tratamos tu mensaje, dirección de correo e información facilitada para responder. El correo se presta mediante Apple iCloud Mail. La base jurídica es el artículo 6, apartado 1, letra f, del RGPD o, para solicitudes precontractuales, su letra b. Los mensajes se eliminan cuando la solicitud queda resuelta, salvo obligación legal de conservación. Puedes consultar la <a href="https://www.apple.com/legal/privacy/en-ww/" target="_blank" rel="noreferrer">política de privacidad de Apple</a>.</p>
    </section>
    <section><h2>8. Conservación y destinatarios</h2>
      <p>Los ajustes locales y las cachés de la aplicación permanecen hasta que se sustituyen automáticamente o los eliminas. Los informes de problemas se conservan como indica la sección 6. Los mensajes de contacto se guardan solo mientras sean necesarios para la solicitud o una obligación legal. Los datos técnicos de seguridad y la analítica agregada de Cloudflare se conservan según lo descrito y sus políticas aplicables. Solo se comunican datos a los proveedores indicados cuando es necesario o cuando lo exige la ley.</p>
    </section>
    <section><h2>9. Tus derechos</h2>
      <p>Cuando se cumplen los requisitos legales, tienes derecho de acceso, rectificación, supresión, limitación del tratamiento y portabilidad, así como a oponerte al tratamiento basado en intereses legítimos. También puedes presentar una reclamación ante una autoridad de protección de datos. Para ejercer tus derechos, escribe al correo indicado arriba.</p>
    </section>
    <section><h2>10. Cambios</h2>
      <p>Esta política se actualizará antes de introducir publicidad, cuentas de usuario, pagos, servicios adicionales de analítica u otros servicios que traten datos adicionales.</p>
    </section>
  </main>;
}
